### PR TITLE
Windows Universal Platform basic support

### PR DESCRIPTION
**Pull request by Davide-sd**
So far tested with Lumia 920 running Windows 10 mobile, everything worked nice and smoothly.

### CODE REVIEW

**Comment by yaroslav-khomyak** [comment]
I've tested this code, it's not working with raw binary data.

**Comment by stakutis** [comment]
I'm anxious for this release.  When might it be done/ready?

**Comment by matRR** [comment]
Is there any chance that this feature will be included in the next release? It would be very nice to have w10 support.

**Comment by don** [comment]
@Davide-sd  I merged this but then reverted it because I couldn't get it to work on Window 10 or Windows 10 phone.

* I had to manually fix the Bluetooth permissions in the manifest
* I can connect, but can't send and receive data.
* list() returns large strings, ideally it will return MAC addresses
* subscribe() and subscribe() raw are using arguments rather than the callbacks

Can you comment on this and re-open the pull request so we can work through the problems?

**Comment by Davide-sd** [comment]
Hello @don, sorry to hear about all these problems. I'm going to take a look ASAP.

**Comment by Davide-sd** [comment]
I've taken a quick look the code in my repository to "wake up" my memory:

> I had to manually fix the Bluetooth permissions in the manifest
Can you explain a bit more in details? At that time I added this code to the plugin.xml. This seemed to let the app to use the BT:
```
<!-- Windows universal apps (Windows 8.1, Windows Phone 8.1, Windows 10) -->
    <platform name="windows">
        <js-module src="src/windows/BluetoothSerial.js" name="BluetoothSerial">
            <merges target="" />
        </js-module>
	
	<config-file target="package.appxmanifest" parent="/Package/Capabilities">
		<DeviceCapability Name="bluetooth.rfcomm">
			<Device Id="any">
				<Function Type="name:serialPort" />
			</Device>
		</DeviceCapability>
         </config-file>
</platform>
```

> I can connect, but can't send and receive data.
This is really strange: when I built this implementation it worked "flawlessly". I tested the code with the classic Arduino controlled RGB LEDs and I was able to send and receive data. 

> list() returns large strings, ideally it will return MAC addresses
Yeah, from what I've seen, Microsoft BT API is far from ideal. As you said, list() returned a very long string ID. At that time, there was no way to get the MAC address from it. I went through all their docs and there was no way to do it :(((

> subscribe() and subscribe() raw are using arguments rather than the callbacks
This is difficult to explain: take a look at the subscribe method in the www/bluetoothSerial.js. You can see I've added the success callback into the arguments array. Why? If you try to call the success callback directly, it is not going to work. I never found out why, I'm not sure if it was a limitation of Microsoft Javascript engine, or some bug in the Cordova engine. The only way to use the success callback (hence receive the data) was to pass it as an arguments.

These are just a few things I remember from the time I spent on it. I would gladly help you to port this into Windows, though my phone crashed some months ago and I happily switched to Android.... As of now I just have a PC (Windows 10 installed too), but no Bluetooth module on it. So I'm not sure what I can do.

**Comment by yaroslav-khomyak** [comment]
I can share my code, which I modified for my project. Original code is not working, so I had to rework it. It can search for devices, connect/disconnect, and subscribe to RAW data.
Maybe it helps.

[cordova-plugin-bluetooth-serial.zip](https://github.com/don/BluetoothSerial/files/850994/cordova-plugin-bluetooth-serial.zip)

**Comment by don** [comment]
@Davide-sd something probably changed in the time it's take me to get to this. I'm pretty sure we can track it down.

I'm trying on Windows 10 and Windows Phone 10. Realistically Windows Phone is dead so I might just look at Windows 10. @mbluewolf is also looking at this as part of #294

@yaroslav-khomyak thanks for sharing you code

**Comment by don** [comment]
@Davide-sd I fixed the subscribe problem. It looks like your device was sending the [length of the data as the first byte](https://github.com/Davide-sd/BluetoothSerial/blob/f44427d6a9e22da7c5adc28e4a05802fed71fd2d/src/windows/BluetoothSerial.js#L60). Now it just reads any data as it arrived. See https://github.com/don/BluetoothSerial/issues/294#issuecomment-287580897 for more details.

**Pull request merged**
