### PR TITLE
Solving issue #127 Uint8Array is not defined

### PR DESCRIPTION
**Pull request by L2Gui**
Hi,

Browsing the Internet, I found a solution to my problem #127 , and so, I think that I should create a pull request, that might help some people too.
I didn't wrote a single line of code (well, 3, but that doesn't matter). All credit goes to notmasteryet ( https://gist.github.com/notmasteryet/1057924 ).

### CODE REVIEW

**Comment by kwetzakwak** [comment]
Woops... Something went wrong between the head and the keyboard... Don't look now, my commit went wrong.

**Comment by kwetzakwak** [comment]
Well, I think that's ok.
The modification works fine on the GT-S5830 (And the Bluetooth still works on the C5303) !

**Comment by don** [comment]
@kwetzakwak thanks for helping make this work on old Android devices

Can you
 * remove the patch for XMLHttpRequest.response
 * remove window.btoa
 * Revert stringToArrayBuffer to original version using Uint8Array. (Windows phone does not have btoa)
 * Add attribution to the original author and gist in the code

After this I'll merge the pull request and move the Uin8Array code to a separate JavaScript file.

**Comment by kwetzakwak** [comment]
Sure for the path for XML, and the author.

Concerning btoa, the patch actually create it as well if missing, as far as I can remember, it didn't work without it. I'll check that tomorrow.

**Comment by don** [comment]
If `stringToArrayBuffer` uses Uint8Array, we should be OK. `window.btoa` can throw an exception with unicode so I'd prefer to use the original `stringToArrayBuffer`.

**Comment by kwetzakwak** [comment]
Ok, I remember why I decided to use btoa. Using your stringToArrayBuffer, I got a problem of encoding... I think the robot I use only works with ASCII. So when I try to send "start" with your function, the robot gets "��^uׯ{�^5׭w"...

I don't know if it's realy due to the robot I use or not, but I get some encoding problems.
I'll try to invertigate that issue later, when i'll import my app to WindowsPhone, to check on the compatibility.

**Comment by don** [comment]
Not merging. Android 2.3 support was dropped from Cordova 5.0. If people need this for older versions they can manually merge or use [typedarray](https://www.npmjs.com/package/typedarray) in their app.

**Pull request closed without merging**
