### PR TITLE
Added listOnReach service for listing bluetooth devices nearby

### PR DESCRIPTION
**Pull request by nuk**
I've added a `listOnReach` service for finding nearby Bluetooth devices.
The code was testes on my NexusOne (running CyanogenMod) and Nexus4 (Android Lolipop) without any issues.

OBS: For the future I'd want to add the capability to list LE devices, but still got to find how not to break on older devices.

### CODE REVIEW

**Comment by don** [comment]
@nuk thanks for the pull request, I'll review and test soon

On iOS BLE already finds nearby devices when scanning, although scan results are limited to the UART services this plugin handles. For BLE on Android or additional BLE services on iOS try https://github.com/don/cordova-plugin-ble-central

**Comment by nuk** [comment]
Nice, I'll look at it.

**Comment by don** [comment]
Manually merged in dd76a60feae7753df59edf1bc45340412a5be198

**Comment by don** [comment]
Renamed the API [discoverUnpaired](https://github.com/don/BluetoothSerial/blob/master/README.md#discoverunpaired)

**Pull request closed without merging**
