### PR TITLE
added device discovery callback

### PR DESCRIPTION
**Pull request by shokre**
added js callback that fires on device discovery

### CODE REVIEW

**Comment by don** [comment]
@shokre I like the idea of sending discovered unpaired devices to the callback as they are received. Do you see any reason not to do this in the original callback instead of adding setDeviceDiscoveredListener and clearDeviceDiscoveredListener?

**Comment by shokre** [comment]
@don do you think of context being passed to discoverUnpairedDevices ?

**Comment by don** [comment]
I was thinking of discoverUnpaired success could be called for every device like setDeviceDiscoveredListener. The disadvantage of that approach is the called doesn't know when the discovery ended. Currently when success for discoverUnpaired is called, you know the discovery is complete.

**Comment by shokre** [comment]
Well, we could add a field on last call that signals that discovery is finished.

But as I see it this will most certainly break all user apps (if there are any) that depend on previous discoverUnpaired implementation. 

Other thing is that cordova plugins' api follow pattern `function (success, failure)`, and calling success multiple times (in this case for notify) would be anti-pattern and counter-intuitive. In my opinion it is better to preserve cordova plugin api pattern and maybe add notify callback option, than break it.

For instance, the way I use cordova api is to wrap them into promises with promisifyAll, and  promissifyAll depends on `function (success, failure)` pattern to work.

Other than that, there is no (technical) reason not to reuse original callback :)

**Comment by don** [comment]
Sounds good. I'll merge as-is.

**Comment by shokre** [comment]
Sorry, I just realized I didn't update README.md.

I'll make a new pull request with updated README.

**Comment by don** [comment]
Updating the README would be great. Thanks!

**Pull request merged**
